name: tech_store
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_common_extensions: ^0.0.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  bloc: ^8.1.2
  firebase_auth: ^4.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

#  assets:


#
#  fonts:
#     - family: Schyler
#       fonts:


